add search bar
chingu-voyages/v48-tier2-team-11 pull request #37
Opened 2024-03-18 18:43 UTC by saswat10

Added the basic search bar functionality. For now it filters the results on the basis of the name of the dinosaur.
![image](https://github.com/chingu-voyages/v48-tier2-team-11/assets/104200293/3c752300-8096-444d-a96c-3c42934d9c79)

2024-03-19 08:49 UTC, PmS-crypto submitted a review, later dismissed

2024-03-19 08:49 UTC, PmS-crypto commented on dinostat/src/Components/DinoList.jsx
> +  }, [pageCounter, dinoDisplayList]);
Just wanted to understand why are we including both pageCounter and dinoDisplayList in the dependency array instead of just pageCounter?

2024-03-22 17:21 UTC, keerthikmr requested changes
### Bug description
The search function stops working when the user is not on the first page.
From what I've seen, I think this is because every time the pageCounter changes, the useEffect statement looks for the second page within the filteredList which does not exist.
_line 39:_
<code>useEffect(() => {<br/>
&nbsp;&nbsp;setDinoDisplayList(filteredList.slice((pageCounter - 1) * 8, pageCounter * 8));<br/>
  }, [pageCounter, dinoDisplayList]);</code>

### Steps to reproduce

1. Upon landing on the dinosaurList page, click on the next page button to navigate to another page
2. Use the search bar to search for dinosaurs

### Other remarks
I think it would be better to convert the filteredList to a state variable. Especially if it eases fixing the bug

2024-03-23 15:28 UTC, saswat10 commented on dinostat/src/Components/DinoList.jsx
> +  }, [pageCounter, dinoDisplayList]);
if we don't pass the pageCounter in the dependency array then on clicking on the up and down button, the page won't update

2024-03-23 17:48 UTC, keerthikmr approved these changes
Great job! Works as expected

2024-03-23 17:49 UTC, merged